title: Overcoming poor programming
description: I read good things about blogging. This is me trying.

author: Luís Sousa Rêgo

baseurl: /Overcoming-poor-programming
url: https://luissousarego.github.io

#theme: no-style-please

# Build settings
remote_theme: riggraz/no-style-please
