title: Overcoming poor programming
description: I read good things about blogging. This is me trying.

author: Luís Sousa Rêgo

baseurl: /Overcoming-poor-programming
url: https://luissousarego.github.io

date_format: "%Y/%m/%d"

skin: custom

# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: ngzhio/jekyll-theme-hamilton
