title: Overcoming poor programming
description: I read good things about blogging. This is me trying.

baseurl: /Overcoming-poor-programming
url: https://luissousarego.github.io

date_format: "%Y/%m/%d"

github_username: luissousarego

skin: custom

# Build settings
plugins:
  - jekyll-remote-theme

remote_theme: ngzhio/jekyll-theme-hamilton
