title: Overcoming poor programming
description: I read good things about blogging. This is me trying.

avatar: /assets/eu.jpg
author: Luís Sousa Rêgo
email: luis.sousa.rego@gmail.com

baseurl: /Overcoming-poor-programming
url: https://luissousarego.github.io

date_format: "%Y/%m/%d"

skin: custom

# Build settings
plugins:
  - jekyll-remote-theme

remote_theme: ngzhio/jekyll-theme-hamilton
